# This is a workflow to get the latest DevCard and download it to my profile

name: daily-devcard

# Controls when the workflow will run
on:
  workflow_dispatch:

  # Triggers the workflow on push request events but only for the "main" branch
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "devcard"
  devcard:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    permissions:
      contents: write

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

      - name: devcard
        uses: dailydotdev/action-devcard@3.0.0
        with:
          user_id: ${{ secrets.USER_ID }}
          commit_message: "chore: update ${filename}"
